### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Cybcast-Site#1]
Missing information:
1. [ ] Content on articles;
2. [ ] Purpose of "more information" in articles;

![screenshot from 2017-05-16 11-05-41](https://cloud.githubusercontent.com/assets/20294485/26095816/b26a339c-3a27-11e7-8d49-a738f6d42cd0.png)
![screenshot from 2017-05-16 11-05-35](https://cloud.githubusercontent.com/assets/20294485/26095825/b529fdba-3a27-11e7-933d-91b1d5865ecb.png)

3. [x] Clients mail.

**Comment by talovdat** [comment]
Client been told to deliverd the content in the next few hours. 
Client mail - _removed due to stupidity_
- I will update Github.

**Comment by MeanEYE** [comment]
Send email through different means other than putting it online.

**Comment by talovdat** [comment]
Due to stupidity, client mail address in Mladen and Iliya's inbox.

**Comment by talovdat** [comment]
Am closing issue.
Issue got fixed.
