### ISSUE TITLE
Internet explorer lightbox issue

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Cybcast-Site#11]
Only on explorer browser when showing the lightbox the picture goes over the text.

![image](https://cloud.githubusercontent.com/assets/26923359/26829154/0f0aaea0-4acd-11e7-8587-a2da5cbd8fc7.png)

**Comment by MeanEYE** [comment]
Ah, that's @iliyaM thinking he's so good he doesn't need testing. As a result he'll go through all the sites, not only this one, and test in IE.

**Comment by iliyaM** [comment]
I checked on FF.
