### ISSUE TITLE
Redesign and functionality for lightbox

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Cybcast-Site#12]
![image](https://user-images.githubusercontent.com/26923359/26920534-f94a499c-4c41-11e7-8d65-8369ba8ff551.png)

**Comment by MeanEYE** [comment]
This is not a lightbox. This is a dialog. Lightbox is for viewing images.

**Comment by talovdat** [comment]
As far as i know it got fixed.
Am i wrong? 
If not, Close issue.

**Comment by MeanEYE** [comment]
Yes it's done.
