### ISSUE TITLE
Min-height of article needs to be lesser. ‏

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Cybcast-Site#13]
Min-height of article needs to be lesser. ‏
Now its 550px make it 500px.

**Comment by MeanEYE** [comment]
Screenshot needed.

**Comment by talovdat** [comment]
![image](https://user-images.githubusercontent.com/26923359/26926209-71fa8e5c-4c55-11e7-816b-f96cdd85d815.png)


Range between button and text.
