### ISSUE TITLE
Uplaod PDF to server and create a link inside light box

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Cybcast-Site#14]
Uplaod PDF to server and create a link to it inside light box.
PDF in Mladen's email.

**Comment by MeanEYE** [comment]
A button needs to be added on dialog which downloads this PDF. Why only in dialog it will forever be a mystery.

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by talovdat** [comment]
Issue is done.
