### ISSUE TITLE
Deploy language file changes

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Cybcast-Site#19]
I have changed a phone number in the language file.
Deployment required. 

![image](https://user-images.githubusercontent.com/26923359/35777124-1ed8c1f2-09b1-11e8-8011-d774df6c455b.png)

![image](https://user-images.githubusercontent.com/26923359/35777131-2b65011a-09b1-11e8-8044-6307f8f47b33.png)

**Comment by MeanEYE** [comment]
English version needs to be updated as well. There's also no need to post what you changed. We have a history of that.

**Comment by talovdat** [comment]
Done.
