### ISSUE TITLE
"for more information" - "למידע נוסף" 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Cybcast-Site#2]

**Comment by MeanEYE** [comment]
We need exact content which will be displayed so that we don't end up fixing what they didn't decide earlier. Once we know what kind of content they intend to show we'll be able to do a proper job.

**Comment by talovdat** [comment]
To avoid issues closing and opening on and on, Am continuing and updaitng this current conversation.

Misha has finished the design,  content and design in Google Drive.

**Comment by MeanEYE** [comment]
I have completely forgotten what this was about and thanks to your expert description I can't recall. So keep updating, but at some point you'll have to explain again.

**Comment by talovdat** [comment]
Adding light box when clicking "For more information" .
Misha has finished the design, content and design in Google Drive.

![image](https://cloud.githubusercontent.com/assets/26923359/26762965/a15f2162-4953-11e7-8599-caf85823db61.png)

**Comment by MeanEYE** [comment]
Good. Thanks. Okay, so we'll load article content using JSON API.
